version: '3'

services:
  web:
    build: .
      #command: gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles  # Mount static files
    expose:
      - 8000
    ports:
      - 8000:8000


volumes:
  postgres_data:
